<h1> An√°lise scf-025-NOSYM </h1>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
from pathlib import Path

<h1>Contas com ibrav = 0.</h1>

In [2]:
dados_energia = !cd ../scf_025_NOSYM.out/; for file in *; do \
    awk '/^!.*total energy/ { print FILENAME ": " $5; found=1 } \
         END { if (!found) print FILENAME ": nan" }' "$file"; \
done

In [3]:
dados_energia

['scf-5.56-1.45-0.25-1.out: -360.34978738',
 'scf-5.56-1.45-0.25-2.out: -360.72667733',
 'scf-5.56-1.45-0.25-3.out: -252.59516638',
 'scf-5.56-1.45-0.25-4.out: -346.62067084',
 'scf-5.56-1.45-0.25-5.out: -359.43543469',
 'scf-5.56-1.49-0.25-1.out: -360.11628790',
 'scf-5.56-1.49-0.25-2.out: -355.27330724',
 'scf-5.56-1.49-0.25-3.out: -310.09440034',
 'scf-5.56-1.49-0.25-4.out: -351.98773029',
 'scf-5.56-1.49-0.25-5.out: -359.34782394',
 'scf-5.56-1.52-0.25-1.out: -341.21488025',
 'scf-5.56-1.52-0.25-2.out: -360.92635835',
 'scf-5.56-1.52-0.25-3.out: -330.95333295',
 'scf-5.56-1.52-0.25-4.out: -125.43468275',
 'scf-5.56-1.52-0.25-5.out: -357.49059354',
 'scf-5.56-1.55-0.25-1.out: -358.74465901',
 'scf-5.56-1.55-0.25-2.out: -360.42488437',
 'scf-5.56-1.55-0.25-3.out: -358.19109281',
 'scf-5.56-1.55-0.25-4.out: -320.64527335',
 'scf-5.56-1.55-0.25-5.out: -356.23942940',
 'scf-5.56-1.58-0.25-1.out: -359.89160376',
 'scf-5.56-1.58-0.25-2.out: -357.07485836',
 'scf-5.56-1.58-0.25-3.out: -360.23957238',
 'scf-5.56-1.58-0.25-4.out: -266.55285772',
 'scf-5.56-1.58-0.25-5.out: -360.09462326',
 'scf-5.56-1.61-0.25-1.out: -356.82359657',
 'scf-5.56-1.61-0.25-2.out: -358.50304155',
 'scf-5.56-1.61-0.25-3.out: -347.11262262',
 'scf-5.56-1.61-0.25-4.out: -360.96370971',
 'scf-5.56-1.61-0.25-5.out: -360.30997488',
 'scf-5.56-1.65-0.25-1.out: -360.07419900',
 'scf-5.56-1.65-0.25-2.out: -358.78433938',
 'scf-5.56-1.65-0.25-3.out: -94.60610844',
 'scf-5.56-1.65-0.25-4.out: -336.69716404',
 'scf-5.56-1.65-0.25-5.out: -359.49209971',
 'scf-5.56-1.68-0.25-1.out: -353.78297632',
 'scf-5.56-1.68-0.25-2.out: -357.99874923',
 'scf-5.56-1.68-0.25-3.out: -359.21732629',
 'scf-5.56-1.68-0.25-4.out: -360.74126873',
 'scf-5.56-1.68-0.25-5.out: -358.90483765',
 'scf-5.56-1.71-0.25-1.out: -359.36119086',
 'scf-5.56-1.71-0.25-2.out: -349.33234061',
 'scf-5.56-1.71-0.25-3.out: -359.59196087',
 'scf-5.56-1.71-0.25-4.out: -350.38541133',
 'scf-5.56-1.71-0.25-5.out: -357.88411091',
 'scf-5.56-1.74-0.25-1.out: -360.36490404',
 'scf-5.56-1.74-0.25-2.out: -358.83687407',
 'scf-5.56-1.74-0.25-3.out: -360.39301630',
 'scf-5.56-1.74-0.25-4.out: -354.74038087',
 'scf-5.56-1.74-0.25-5.out: -354.95044865',
 'scf-5.56-1.78-0.25-1.out: -350.28614471',
 'scf-5.56-1.78-0.25-2.out: -357.44131777',
 'scf-5.56-1.78-0.25-3.out: -352.81948383',
 'scf-5.56-1.78-0.25-4.out: -360.06294447',
 'scf-5.56-1.78-0.25-5.out: -360.12465509',
 'scf-5.68-1.45-0.25-1.out: -360.81576999',
 'scf-5.68-1.45-0.25-2.out: -357.85363499',
 'scf-5.68-1.45-0.25-3.out: -360.65318546',
 'scf-5.68-1.45-0.25-4.out: -359.51191954',
 'scf-5.68-1.45-0.25-5.out: -359.65732761',
 'scf-5.68-1.49-0.25-1.out: -361.02161741',
 'scf-5.68-1.49-0.25-2.out: -361.11214815',
 'scf-5.68-1.49-0.25-3.out: -360.63165270',
 'scf-5.68-1.49-0.25-4.out: -329.89652234',
 'scf-5.68-1.49-0.25-5.out: -359.32551490',
 'scf-5.68-1.52-0.25-1.out: -328.21309458',
 'scf-5.68-1.52-0.25-2.out: -329.59867322',
 'scf-5.68-1.52-0.25-3.out: -360.65406051',
 'scf-5.68-1.52-0.25-4.out: -356.74399817',
 'scf-5.68-1.52-0.25-5.out: -360.74399458',
 'scf-5.68-1.55-0.25-1.out: -349.82809933',
 'scf-5.68-1.55-0.25-2.out: -360.87141144',
 'scf-5.68-1.55-0.25-3.out: -349.34543137',
 'scf-5.68-1.55-0.25-4.out: -329.97723327',
 'scf-5.68-1.55-0.25-5.out: -361.13897940',
 'scf-5.68-1.58-0.25-1.out: -348.77588553',
 'scf-5.68-1.58-0.25-2.out: 339.70505703',
 'scf-5.68-1.58-0.25-3.out: -361.02160769',
 'scf-5.68-1.58-0.25-4.out: -339.10373938',
 'scf-5.68-1.58-0.25-5.out: -360.85900220',
 'scf-5.68-1.61-0.25-1.out: -311.09963542',
 'scf-5.68-1.61-0.25-2.out: -359.76586603',
 'scf-5.68-1.61-0.25-3.out: -352.35782621',
 'scf-5.68-1.61-0.25-4.out: -359.45098610',
 'scf-5.68-1.61-0.25-5.out: -361.20993096',
 'scf-5.68-1.65-0.25-1.out: -360.34732610',
 'scf-5.68-1.65-0.25-2.out: -361.22645087',
 'scf-5.68-1.65-0.25-3.out: -336.68249671',
 'scf-5.68-1.65-0.25-4.out: -361.00235408',
 'scf-5.68-1.65-0.25-5.out: -342.51477144',
 'scf-5.68-1.68-0.25-1.out: -361.22981585',
 'scf-5.68-1.68-0.25-2.out: -359.27245693',
 'scf-5.68-1.68-0.25-3.out: -334.13224657',
 'scf-5.68-1.68-0.25-4.out: -360.30538069',
 'scf-5.68-1.68-0.25-5.out: -348.30523071',
 'scf-5.68-1.71-0.25-1.out: -360.78795053',
 'scf-5.68-1.71-0.25-2.out: -360.53985982',
 'scf-5.68-1.71-0.25-3.out: -359.80811112',
 'scf-5.68-1.71-0.25-4.out: -318.77487486',
 'scf-5.68-1.71-0.25-5.out: -359.27738233',
 'scf-5.68-1.74-0.25-1.out: -359.26265028',
 'scf-5.68-1.74-0.25-2.out: -351.96926691',
 'scf-5.68-1.74-0.25-3.out: -360.66946700',
 'scf-5.68-1.74-0.25-4.out: -359.87367731',
 'scf-5.68-1.74-0.25-5.out: -352.05287993',
 'scf-5.68-1.78-0.25-1.out: -359.35952289',
 'scf-5.68-1.78-0.25-2.out: -361.04334608',
 'scf-5.68-1.78-0.25-3.out: -360.84125933',
 'scf-5.68-1.78-0.25-4.out: -357.79252606',
 'scf-5.68-1.78-0.25-5.out: -351.67066908',
 'scf-5.81-1.45-0.25-1.out: -360.79400919',
 'scf-5.81-1.45-0.25-2.out: -360.46778929',
 'scf-5.81-1.45-0.25-3.out: -355.05514197',
 'scf-5.81-1.45-0.25-4.out: -355.89319261',
 'scf-5.81-1.45-0.25-5.out: -360.87247969',
 'scf-5.81-1.49-0.25-1.out: -360.24676812',
 'scf-5.81-1.49-0.25-2.out: -359.91839809',
 'scf-5.81-1.49-0.25-3.out: -359.89301423',
 'scf-5.81-1.49-0.25-4.out: -358.83556713',
 'scf-5.81-1.49-0.25-5.out: -360.64565798',
 'scf-5.81-1.52-0.25-1.out: -359.81366961',
 'scf-5.81-1.52-0.25-2.out: -345.47217444',
 'scf-5.81-1.52-0.25-3.out: -357.31936201',
 'scf-5.81-1.52-0.25-4.out: -360.30756960',
 'scf-5.81-1.52-0.25-5.out: -357.60465526',
 'scf-5.81-1.55-0.25-1.out: -354.00342622',
 'scf-5.81-1.55-0.25-2.out: -360.63841896',
 'scf-5.81-1.55-0.25-3.out: -360.67194886',
 'scf-5.81-1.55-0.25-4.out: -352.28314882',
 'scf-5.81-1.55-0.25-5.out: -361.14536463',
 'scf-5.81-1.58-0.25-1.out: -307.71026364',
 'scf-5.81-1.58-0.25-2.out: -356.98318196',
 'scf-5.81-1.58-0.25-3.out: -121.19121875',
 'scf-5.81-1.58-0.25-4.out: -358.94636977',
 'scf-5.81-1.58-0.25-5.out: -359.98562182',
 'scf-5.81-1.61-0.25-1.out: -361.10139535',
 'scf-5.81-1.61-0.25-2.out: 603.66517109',
 'scf-5.81-1.61-0.25-3.out: -359.91603196',
 'scf-5.81-1.61-0.25-4.out: -360.67924990',
 'scf-5.81-1.61-0.25-5.out: -361.02186592',
 'scf-5.81-1.65-0.25-1.out: -357.11043443',
 'scf-5.81-1.65-0.25-2.out: -359.15133219',
 'scf-5.81-1.65-0.25-3.out: -360.68242667',
 'scf-5.81-1.65-0.25-4.out: -359.60681581',
 'scf-5.81-1.65-0.25-5.out: -359.80506413',
 'scf-5.81-1.68-0.25-1.out: -361.32590472',
 'scf-5.81-1.68-0.25-2.out: -347.10469339',
 'scf-5.81-1.68-0.25-3.out: -352.51559368',
 'scf-5.81-1.68-0.25-4.out: -354.07692832',
 'scf-5.81-1.68-0.25-5.out: -358.06856406',
 'scf-5.81-1.71-0.25-1.out: -360.04012877',
 'scf-5.81-1.71-0.25-2.out: -339.25881399',
 'scf-5.81-1.71-0.25-3.out: -360.01620153',
 'scf-5.81-1.71-0.25-4.out: -360.45154995',
 'scf-5.81-1.71-0.25-5.out: -271.44694837',
 'scf-5.81-1.74-0.25-1.out: -341.48234772',
 'scf-5.81-1.74-0.25-2.out: -354.84910303',
 'scf-5.81-1.74-0.25-3.out: -360.38835240',
 'scf-5.81-1.74-0.25-4.out: -360.13777448',
 'scf-5.81-1.74-0.25-5.out: -360.52218118',
 'scf-5.81-1.78-0.25-1.out: -358.31629673',
 'scf-5.81-1.78-0.25-2.out: -346.04374636',
 'scf-5.81-1.78-0.25-3.out: -359.22147142',
 'scf-5.81-1.78-0.25-4.out: -350.17713429',
 'scf-5.81-1.78-0.25-5.out: -353.45874651',
 'scf-5.93-1.45-0.25-1.out: -360.05188656',
 'scf-5.93-1.45-0.25-2.out: -360.65055017',
 'scf-5.93-1.45-0.25-3.out: -357.83456683',
 'scf-5.93-1.45-0.25-4.out: -360.70885134',
 'scf-5.93-1.45-0.25-5.out: -359.83366011',
 'scf-5.93-1.49-0.25-1.out: -359.97038057',
 'scf-5.93-1.49-0.25-2.out: -360.98907166',
 'scf-5.93-1.49-0.25-3.out: -361.09513196',
 'scf-5.93-1.49-0.25-4.out: -360.70075213',
 'scf-5.93-1.49-0.25-5.out: -359.82312846',
 'scf-5.93-1.52-0.25-1.out: -358.82471879',
 'scf-5.93-1.52-0.25-2.out: -358.73841279',
 'scf-5.93-1.52-0.25-3.out: -357.72710112',
 'scf-5.93-1.52-0.25-4.out: -351.76360836',
 'scf-5.93-1.52-0.25-5.out: -356.92410169',
 'scf-5.93-1.55-0.25-1.out: -361.33932967',
 'scf-5.93-1.55-0.25-2.out: -357.25376677',
 'scf-5.93-1.55-0.25-3.out: -358.88620684',
 'scf-5.93-1.55-0.25-4.out: -359.72950747',
 'scf-5.93-1.55-0.25-5.out: -361.01539128',
 'scf-5.93-1.58-0.25-1.out: -360.40767662',
 'scf-5.93-1.58-0.25-2.out: -306.87639357',
 'scf-5.93-1.58-0.25-3.out: -360.06856316',
 'scf-5.93-1.58-0.25-4.out: -358.73894856',
 'scf-5.93-1.58-0.25-5.out: -359.87098124',
 'scf-5.93-1.61-0.25-1.out: -361.05838984',
 'scf-5.93-1.61-0.25-2.out: -360.76683081',
 'scf-5.93-1.61-0.25-3.out: -359.82665732',
 'scf-5.93-1.61-0.25-4.out: -361.01907422',
 'scf-5.93-1.61-0.25-5.out: -353.91865671',
 'scf-5.93-1.65-0.25-1.out: -350.73457101',
 'scf-5.93-1.65-0.25-2.out: -359.83083018',
 'scf-5.93-1.65-0.25-3.out: -354.67961285',
 'scf-5.93-1.65-0.25-4.out: -361.05370868',
 'scf-5.93-1.65-0.25-5.out: -360.73945263',
 'scf-5.93-1.68-0.25-1.out: -360.81461978',
 'scf-5.93-1.68-0.25-2.out: -343.50040960',
 'scf-5.93-1.68-0.25-3.out: -359.63664048',
 'scf-5.93-1.68-0.25-4.out: -356.98389942',
 'scf-5.93-1.68-0.25-5.out: -330.53558893',
 'scf-5.93-1.71-0.25-1.out: -361.15494937',
 'scf-5.93-1.71-0.25-2.out: -349.37813565',
 'scf-5.93-1.71-0.25-3.out: -361.21945897',
 'scf-5.93-1.71-0.25-4.out: -333.60468357',
 'scf-5.93-1.71-0.25-5.out: -355.00228811',
 'scf-5.93-1.74-0.25-1.out: -361.02582076',
 'scf-5.93-1.74-0.25-2.out: -356.77221358',
 'scf-5.93-1.74-0.25-3.out: -152.16560590',
 'scf-5.93-1.74-0.25-4.out: -352.30889521',
 'scf-5.93-1.74-0.25-5.out: -316.92424802',
 'scf-5.93-1.78-0.25-1.out: -361.46769601',
 'scf-5.93-1.78-0.25-2.out: -361.03623383',
 'scf-5.93-1.78-0.25-3.out: -360.42679895',
 'scf-5.93-1.78-0.25-4.out: -352.88359553',
 'scf-5.93-1.78-0.25-5.out: -354.86486213',
 'scf-6.06-1.45-0.25-1.out: -355.91712500',
 'scf-6.06-1.45-0.25-2.out: -354.59864195',
 'scf-6.06-1.45-0.25-3.out: -360.16306819',
 'scf-6.06-1.45-0.25-4.out: -360.19061659',
 'scf-6.06-1.45-0.25-5.out: -357.14695774',
 'scf-6.06-1.49-0.25-1.out: -353.05981043',
 'scf-6.06-1.49-0.25-2.out: -353.23877898',
 'scf-6.06-1.49-0.25-3.out: -359.17564862',
 'scf-6.06-1.49-0.25-4.out: -361.36634741',
 'scf-6.06-1.49-0.25-5.out: -358.48137437',
 'scf-6.06-1.52-0.25-1.out: -360.01748999',
 'scf-6.06-1.52-0.25-2.out: -357.51813559',
 'scf-6.06-1.52-0.25-3.out: 207.61874211',
 'scf-6.06-1.52-0.25-4.out: -359.10620730',
 'scf-6.06-1.52-0.25-5.out: -361.37711369',
 'scf-6.06-1.55-0.25-1.out: -360.63669788',
 'scf-6.06-1.55-0.25-2.out: -359.28259042',
 'scf-6.06-1.55-0.25-3.out: -360.53389709',
 'scf-6.06-1.55-0.25-4.out: -349.62266181',
 'scf-6.06-1.55-0.25-5.out: -359.15602891',
 'scf-6.06-1.58-0.25-1.out: -361.33474317',
 'scf-6.06-1.58-0.25-2.out: -358.28818535',
 'scf-6.06-1.58-0.25-3.out: -360.83086924',
 'scf-6.06-1.58-0.25-4.out: -360.39557065',
 'scf-6.06-1.58-0.25-5.out: -360.49358902',
 'scf-6.06-1.61-0.25-1.out: -360.70329848',
 'scf-6.06-1.61-0.25-2.out: -360.77341793',
 'scf-6.06-1.61-0.25-3.out: -359.82316361',
 'scf-6.06-1.61-0.25-4.out: -298.35153606',
 'scf-6.06-1.61-0.25-5.out: -359.61408212',
 'scf-6.06-1.65-0.25-1.out: -316.57995640',
 'scf-6.06-1.65-0.25-2.out: -360.27650043',
 'scf-6.06-1.65-0.25-3.out: -360.98266442',
 'scf-6.06-1.65-0.25-4.out: -341.02669114',
 'scf-6.06-1.65-0.25-5.out: -359.77241932',
 'scf-6.06-1.68-0.25-1.out: -337.21277189',
 'scf-6.06-1.68-0.25-2.out: -361.34491775',
 'scf-6.06-1.68-0.25-3.out: -360.18998330',
 'scf-6.06-1.68-0.25-4.out: -338.44460210',
 'scf-6.06-1.68-0.25-5.out: -341.32549680',
 'scf-6.06-1.71-0.25-1.out: -347.06963111',
 'scf-6.06-1.71-0.25-2.out: -361.16485260',
 'scf-6.06-1.71-0.25-3.out: -361.40086439',
 'scf-6.06-1.71-0.25-4.out: -357.23785072',
 'scf-6.06-1.71-0.25-5.out: -360.54845659',
 'scf-6.06-1.74-0.25-1.out: -357.56942128',
 'scf-6.06-1.74-0.25-2.out: -360.52766263',
 'scf-6.06-1.74-0.25-3.out: -358.67109682',
 'scf-6.06-1.74-0.25-4.out: -358.19934817',
 'scf-6.06-1.74-0.25-5.out: -361.09402732',
 'scf-6.06-1.78-0.25-1.out: -358.54839655',
 'scf-6.06-1.78-0.25-2.out: -354.31714559',
 'scf-6.06-1.78-0.25-3.out: -360.83464095',
 'scf-6.06-1.78-0.25-4.out: -360.32511229',
 'scf-6.06-1.78-0.25-5.out: -359.72326670',
 'scf-6.18-1.45-0.25-1.out: -361.25152701',
 'scf-6.18-1.45-0.25-2.out: -360.46896806',
 'scf-6.18-1.45-0.25-3.out: -350.37363396',
 'scf-6.18-1.45-0.25-4.out: -361.18599091',
 'scf-6.18-1.45-0.25-5.out: -359.20264294',
 'scf-6.18-1.49-0.25-1.out: nan',
 'scf-6.18-1.49-0.25-2.out: -359.00310631',
 'scf-6.18-1.49-0.25-3.out: -359.96303792',
 'scf-6.18-1.49-0.25-4.out: -351.14266499',
 'scf-6.18-1.49-0.25-5.out: -304.10482092',
 'scf-6.18-1.52-0.25-1.out: -360.71289085',
 'scf-6.18-1.52-0.25-2.out: -354.95695658',
 'scf-6.18-1.52-0.25-3.out: -359.60923394',
 'scf-6.18-1.52-0.25-4.out: -361.50831455',
 'scf-6.18-1.52-0.25-5.out: -360.87741697',
 'scf-6.18-1.55-0.25-1.out: -360.47435291',
 'scf-6.18-1.55-0.25-2.out: -305.21509595',
 'scf-6.18-1.55-0.25-3.out: -361.40979481',
 'scf-6.18-1.55-0.25-4.out: -361.38469321',
 'scf-6.18-1.55-0.25-5.out: -357.46184823',
 'scf-6.18-1.58-0.25-1.out: -357.10705495',
 'scf-6.18-1.58-0.25-2.out: -358.47490887',
 'scf-6.18-1.58-0.25-3.out: -361.46609091',
 'scf-6.18-1.58-0.25-4.out: -360.54592447',
 'scf-6.18-1.58-0.25-5.out: -359.97957004',
 'scf-6.18-1.61-0.25-1.out: -360.58078373',
 'scf-6.18-1.61-0.25-2.out: -361.27794600',
 'scf-6.18-1.61-0.25-3.out: -358.43509295',
 'scf-6.18-1.61-0.25-4.out: -359.23606750',
 'scf-6.18-1.61-0.25-5.out: -359.94031103',
 'scf-6.18-1.65-0.25-1.out: -357.22323025',
 'scf-6.18-1.65-0.25-2.out: -356.60513204',
 'scf-6.18-1.65-0.25-3.out: -361.07816042',
 'scf-6.18-1.65-0.25-4.out: -325.34856794',
 'scf-6.18-1.65-0.25-5.out: -360.33950470',
 'scf-6.18-1.68-0.25-1.out: -330.66576675',
 'scf-6.18-1.68-0.25-2.out: -344.10151316',
 'scf-6.18-1.68-0.25-3.out: -361.16200681',
 'scf-6.18-1.68-0.25-4.out: -361.16898302',
 'scf-6.18-1.68-0.25-5.out: -360.60536754',
 'scf-6.18-1.71-0.25-1.out: -359.22603201',
 'scf-6.18-1.71-0.25-2.out: -357.73098425',
 'scf-6.18-1.71-0.25-3.out: -356.40104610',
 'scf-6.18-1.71-0.25-4.out: -361.28439902',
 'scf-6.18-1.71-0.25-5.out: -360.08164915',
 'scf-6.18-1.74-0.25-1.out: -360.60577438',
 'scf-6.18-1.74-0.25-2.out: -361.29186658',
 'scf-6.18-1.74-0.25-3.out: -360.38394539',
 'scf-6.18-1.74-0.25-4.out: -360.49822535',
 'scf-6.18-1.74-0.25-5.out: -360.41140680',
 'scf-6.18-1.78-0.25-1.out: -357.76814560',
 'scf-6.18-1.78-0.25-2.out: -360.73361908',
 'scf-6.18-1.78-0.25-3.out: -354.97181501',
 'scf-6.18-1.78-0.25-4.out: -360.21955710',
 'scf-6.18-1.78-0.25-5.out: -355.70212817',
 'scf-6.30-1.45-0.25-1.out: -360.28811636',
 'scf-6.30-1.45-0.25-2.out: -360.51499937',
 'scf-6.30-1.45-0.25-3.out: -359.86423090',
 'scf-6.30-1.45-0.25-4.out: -360.27779124',
 'scf-6.30-1.45-0.25-5.out: -361.00084695',
 'scf-6.30-1.49-0.25-1.out: -350.28939756',
 'scf-6.30-1.49-0.25-2.out: -353.27323964',
 'scf-6.30-1.49-0.25-3.out: -319.15732843',
 'scf-6.30-1.49-0.25-4.out: -334.03182028',
 'scf-6.30-1.49-0.25-5.out: -359.19691892',
 'scf-6.30-1.52-0.25-1.out: -360.35908675',
 'scf-6.30-1.52-0.25-2.out: -361.35113556',
 'scf-6.30-1.52-0.25-3.out: -361.47560084',
 'scf-6.30-1.52-0.25-4.out: -361.10762217',
 'scf-6.30-1.52-0.25-5.out: -361.11320851',
 'scf-6.30-1.55-0.25-1.out: -361.02006317',
 'scf-6.30-1.55-0.25-2.out: -360.77691998',
 'scf-6.30-1.55-0.25-3.out: -352.37982371',
 'scf-6.30-1.55-0.25-4.out: -361.05893068',
 'scf-6.30-1.55-0.25-5.out: -361.35222651',
 'scf-6.30-1.58-0.25-1.out: -360.50489421',
 'scf-6.30-1.58-0.25-2.out: -330.81028691',
 'scf-6.30-1.58-0.25-3.out: -360.90850374',
 'scf-6.30-1.58-0.25-4.out: -360.51859711',
 'scf-6.30-1.58-0.25-5.out: -359.99715839',
 'scf-6.30-1.61-0.25-1.out: -349.38713047',
 'scf-6.30-1.61-0.25-2.out: -360.77509788',
 'scf-6.30-1.61-0.25-3.out: -361.12850620',
 'scf-6.30-1.61-0.25-4.out: -336.42797123',
 'scf-6.30-1.61-0.25-5.out: -354.77940190',
 'scf-6.30-1.65-0.25-1.out: -358.76309899',
 'scf-6.30-1.65-0.25-2.out: -361.03002683',
 'scf-6.30-1.65-0.25-3.out: -344.34517927',
 'scf-6.30-1.65-0.25-4.out: -359.68118256',
 'scf-6.30-1.65-0.25-5.out: -358.73309511',
 'scf-6.30-1.68-0.25-1.out: -357.84825360',
 'scf-6.30-1.68-0.25-2.out: -360.41442784',
 'scf-6.30-1.68-0.25-3.out: -356.78790965',
 'scf-6.30-1.68-0.25-4.out: -356.25256702',
 'scf-6.30-1.68-0.25-5.out: -360.67208818',
 'scf-6.30-1.71-0.25-1.out: -335.47242925',
 'scf-6.30-1.71-0.25-2.out: -359.93506811',
 'scf-6.30-1.71-0.25-3.out: -361.26668133',
 'scf-6.30-1.71-0.25-4.out: -360.93371015',
 'scf-6.30-1.71-0.25-5.out: -345.95566833',
 'scf-6.30-1.74-0.25-1.out: -361.49158030',
 'scf-6.30-1.74-0.25-2.out: -360.13881971',
 'scf-6.30-1.74-0.25-3.out: -305.73392214',
 'scf-6.30-1.74-0.25-4.out: -361.10424404',
 'scf-6.30-1.74-0.25-5.out: -344.86093251',
 'scf-6.30-1.78-0.25-1.out: -360.80127758',
 'scf-6.30-1.78-0.25-2.out: -360.73647236',
 'scf-6.30-1.78-0.25-3.out: -360.68767048',
 'scf-6.30-1.78-0.25-4.out: -361.31320299',
 'scf-6.30-1.78-0.25-5.out: -359.56123121',
 'scf-6.43-1.45-0.25-1.out: -361.24547031',
 'scf-6.43-1.45-0.25-2.out: -357.42155522',
 'scf-6.43-1.45-0.25-3.out: -351.63137478',
 'scf-6.43-1.45-0.25-4.out: nan',
 'scf-6.43-1.45-0.25-5.out: -361.51945620',
 'scf-6.43-1.49-0.25-1.out: -360.95691980',
 'scf-6.43-1.49-0.25-2.out: -358.21927259',
 'scf-6.43-1.49-0.25-3.out: -361.40855799',
 'scf-6.43-1.49-0.25-4.out: -361.29785279',
 'scf-6.43-1.49-0.25-5.out: -356.80423187',
 'scf-6.43-1.52-0.25-1.out: -349.30028347',
 'scf-6.43-1.52-0.25-2.out: -361.50980623',
 'scf-6.43-1.52-0.25-3.out: -360.28350343',
 'scf-6.43-1.52-0.25-4.out: -361.37634890',
 'scf-6.43-1.52-0.25-5.out: -361.00270386',
 'scf-6.43-1.55-0.25-1.out: -344.85810821',
 'scf-6.43-1.55-0.25-2.out: -360.90350876',
 'scf-6.43-1.55-0.25-3.out: -360.90260160',
 'scf-6.43-1.55-0.25-4.out: -360.72428060',
 'scf-6.43-1.55-0.25-5.out: -341.75503806',
 'scf-6.43-1.58-0.25-1.out: -358.83645179',
 'scf-6.43-1.58-0.25-2.out: -361.19873900',
 'scf-6.43-1.58-0.25-3.out: -342.17815350',
 'scf-6.43-1.58-0.25-4.out: -359.95409706',
 'scf-6.43-1.58-0.25-5.out: -360.86261518',
 'scf-6.43-1.61-0.25-1.out: -361.02653691',
 'scf-6.43-1.61-0.25-2.out: -360.08203953',
 'scf-6.43-1.61-0.25-3.out: -358.16663618',
 'scf-6.43-1.61-0.25-4.out: -360.35138326',
 'scf-6.43-1.61-0.25-5.out: -360.76474669',
 'scf-6.43-1.65-0.25-1.out: -360.82114195',
 'scf-6.43-1.65-0.25-2.out: -359.24499148',
 'scf-6.43-1.65-0.25-3.out: -361.12051751',
 'scf-6.43-1.65-0.25-4.out: -359.95052545',
 'scf-6.43-1.65-0.25-5.out: -361.15132216',
 'scf-6.43-1.68-0.25-1.out: -360.93906346',
 'scf-6.43-1.68-0.25-2.out: -360.31498352',
 'scf-6.43-1.68-0.25-3.out: -361.29401873',
 'scf-6.43-1.68-0.25-4.out: -356.93995422',
 'scf-6.43-1.68-0.25-5.out: -360.73050174',
 'scf-6.43-1.71-0.25-1.out: -360.03302922',
 'scf-6.43-1.71-0.25-2.out: -360.44144360',
 'scf-6.43-1.71-0.25-3.out: -360.73870137',
 'scf-6.43-1.71-0.25-4.out: -361.14745306',
 'scf-6.43-1.71-0.25-5.out: -360.39343566',
 'scf-6.43-1.74-0.25-1.out: -358.66564807',
 'scf-6.43-1.74-0.25-2.out: -359.19652239',
 'scf-6.43-1.74-0.25-3.out: -361.07073717',
 'scf-6.43-1.74-0.25-4.out: -360.58894146',
 'scf-6.43-1.74-0.25-5.out: -354.72880696',
 'scf-6.43-1.78-0.25-1.out: -358.00042766',
 'scf-6.43-1.78-0.25-2.out: -361.12746278',
 'scf-6.43-1.78-0.25-3.out: -352.16115653',
 'scf-6.43-1.78-0.25-4.out: -361.33537528',
 'scf-6.43-1.78-0.25-5.out: -360.71218762',
 'scf-6.55-1.45-0.25-1.out: -360.53263803',
 'scf-6.55-1.45-0.25-2.out: -361.30541282',
 'scf-6.55-1.45-0.25-3.out: -341.00535872',
 'scf-6.55-1.45-0.25-4.out: nan',
 'scf-6.55-1.45-0.25-5.out: -208.34105329',
 'scf-6.55-1.49-0.25-1.out: -360.95727485',
 'scf-6.55-1.49-0.25-2.out: -361.21009604',
 'scf-6.55-1.49-0.25-3.out: -359.59902330',
 'scf-6.55-1.49-0.25-4.out: -361.40020831',
 'scf-6.55-1.49-0.25-5.out: -341.11339411',
 'scf-6.55-1.52-0.25-1.out: -361.23943850',
 'scf-6.55-1.52-0.25-2.out: -361.46533883',
 'scf-6.55-1.52-0.25-3.out: -359.89158857',
 'scf-6.55-1.52-0.25-4.out: -361.55411863',
 'scf-6.55-1.52-0.25-5.out: -344.17556467',

In [4]:
dados_energia = [ valor.split(': ',) for valor in dados_energia ]

In [5]:
df = pd.DataFrame(dados_energia, columns=["Arquivo", "Energia Total"])
df

                      Arquivo  Energia Total
0    scf-5.56-1.45-0.25-1.out  -360.34978738
1    scf-5.56-1.45-0.25-2.out  -360.72667733
2    scf-5.56-1.45-0.25-3.out  -252.59516638
3    scf-5.56-1.45-0.25-4.out  -346.62067084
4    scf-5.56-1.45-0.25-5.out  -359.43543469
..                        ...            ...
600  scf-6.80-1.78-0.25-1.out  -361.24999152
601  scf-6.80-1.78-0.25-2.out  -361.36332176
602  scf-6.80-1.78-0.25-3.out            nan
603  scf-6.80-1.78-0.25-4.out  -361.35382618
604  scf-6.80-1.78-0.25-5.out  -361.48262790

[605 rows x 2 columns]

In [6]:
df['Energia Total'] = df['Energia Total'].astype(float)

Regex para adicionar colunas no DataFrame.
```python
    match_nome = re.match(r'scf-([0-9.]+)-([0-9.]+)-(\d+)\.out', arquivo.name)
    if match_nome:
        a = float(match_nome.group(1))
        ratio_ca = float(match_nome.group(2))
        num_estrutura = int(match_nome.group(3))
    else:
        raise ValueError(f'Nome de arquivo n√£o reconhecido: {arquivo.name}')

```

In [7]:
# Supondo que seu DataFrame se chame df
df[['a', 'ratio_ca', 'num_estrutura']] = df['Arquivo'].str.extract(
    r'scf-([0-9.]+)-([0-9.]+)-[0-9.]+-([0-9]+)\.out'
)

# Convertendo para os tipos num√©ricos apropriados
df['a'] = df['a'].astype(float)
df['ratio_ca'] = df['ratio_ca'].astype(float)
df['num_estrutura'] = df['num_estrutura'].astype(int)

In [25]:
df

                      Arquivo  Energia Total     a  ratio_ca  num_estrutura
0    scf-5.56-1.45-0.25-1.out    -360.349787  5.56      1.45              1
1    scf-5.56-1.45-0.25-2.out    -360.726677  5.56      1.45              2
2    scf-5.56-1.45-0.25-3.out    -252.595166  5.56      1.45              3
3    scf-5.56-1.45-0.25-4.out    -346.620671  5.56      1.45              4
4    scf-5.56-1.45-0.25-5.out    -359.435435  5.56      1.45              5
..                        ...            ...   ...       ...            ...
600  scf-6.80-1.78-0.25-1.out    -361.249992  6.80      1.78              1
601  scf-6.80-1.78-0.25-2.out    -361.363322  6.80      1.78              2
602  scf-6.80-1.78-0.25-3.out            NaN  6.80      1.78              3
603  scf-6.80-1.78-0.25-4.out    -361.353826  6.80      1.78              4
604  scf-6.80-1.78-0.25-5.out    -361.482628  6.80      1.78              5

[605 rows x 5 columns]

In [8]:
# Agrupando por estrutura
df1 = df[df['num_estrutura'] == 1]
df2 = df[df['num_estrutura'] == 2]
df3 = df[df['num_estrutura'] == 3]
df4 = df[df['num_estrutura'] == 4]
df5 = df[df['num_estrutura'] == 5]

lista_dfs = [df1, df2, df3,df4,df5]

<h1>Contas com ibrav = 4.</h1>

In [9]:
dados_energia_sym = !cd ../scfs_rnd025.out/; for file in *; do \
    awk '/^!.*total energy/ { print FILENAME ": " $5; found=1 } \
         END { if (!found) print FILENAME ": nan" }' "$file"; \
done

In [10]:
print(dados_energia_sym[0])
print(dados_energia[0])

scf-5.56-1.45-1.out: -355.27569117
['scf-5.56-1.45-0.25-1.out', '-360.34978738']

In [11]:
dados_energia_sym =  [ valor.split(': ',) for valor in dados_energia_sym ]

In [12]:
df_sym = pd.DataFrame(dados_energia_sym, columns=["Arquivo", "Energia Total"])
df_sym['Energia Total'] = df_sym['Energia Total'].astype(float)


df_sym

                 Arquivo  Energia Total
0    scf-5.56-1.45-1.out    -355.275691
1    scf-5.56-1.45-2.out    -360.200615
2    scf-5.56-1.45-3.out    -348.269961
3    scf-5.56-1.45-4.out    -351.847007
4    scf-5.56-1.45-5.out    -359.733879
..                   ...            ...
600  scf-6.80-1.78-1.out            NaN
601  scf-6.80-1.78-2.out    -361.332510
602  scf-6.80-1.78-3.out            NaN
603  scf-6.80-1.78-4.out    -360.331107
604  scf-6.80-1.78-5.out    -360.905143

[605 rows x 2 columns]

In [13]:
# Regex que funciona para ambos os casos:
pattern = r'scf-([0-9.]+)-([0-9.]+)(?:-([0-9.]+))?-([0-9]+)\.out'

df_sym[['a', 'ratio_ca','valor_opcional','num_estrutura']] = df_sym['Arquivo'].str.extract(
    pattern   # ? ? trata como opcional 
)

# Convertendo para os tipos num√©ricos apropriados
df_sym['a'] = df_sym['a'].astype(float)
df_sym['ratio_ca'] = df_sym['ratio_ca'].astype(float)
df_sym['num_estrutura'] = df_sym['num_estrutura'].astype(int)


# Tratando os nulos 
df_sym = df_sym.drop(columns=['valor_opcional'])



df_sym

                 Arquivo  Energia Total     a  ratio_ca  num_estrutura
0    scf-5.56-1.45-1.out    -355.275691  5.56      1.45              1
1    scf-5.56-1.45-2.out    -360.200615  5.56      1.45              2
2    scf-5.56-1.45-3.out    -348.269961  5.56      1.45              3
3    scf-5.56-1.45-4.out    -351.847007  5.56      1.45              4
4    scf-5.56-1.45-5.out    -359.733879  5.56      1.45              5
..                   ...            ...   ...       ...            ...
600  scf-6.80-1.78-1.out            NaN  6.80      1.78              1
601  scf-6.80-1.78-2.out    -361.332510  6.80      1.78              2
602  scf-6.80-1.78-3.out            NaN  6.80      1.78              3
603  scf-6.80-1.78-4.out    -360.331107  6.80      1.78              4
604  scf-6.80-1.78-5.out    -360.905143  6.80      1.78              5

[605 rows x 5 columns]

In [14]:
# Contas em que a energia n√£o convergiu no ibrav = 4.
df_sym[
    df_sym['Energia Total'].isna()
]

                 Arquivo  Energia Total     a  ratio_ca  num_estrutura
109  scf-5.68-1.78-5.out            NaN  5.68      1.78              5
207  scf-5.93-1.71-3.out            NaN  5.93      1.71              3
248  scf-6.06-1.61-4.out            NaN  6.06      1.61              4
323  scf-6.18-1.74-4.out            NaN  6.18      1.74              4
329  scf-6.18-1.78-5.out            NaN  6.18      1.78              5
379  scf-6.30-1.74-5.out            NaN  6.30      1.74              5
407  scf-6.43-1.58-3.out            NaN  6.43      1.58              3
423  scf-6.43-1.68-4.out            NaN  6.43      1.68              4
436  scf-6.43-1.78-2.out            NaN  6.43      1.78              2
475  scf-6.55-1.68-1.out            NaN  6.55      1.68              1
525  scf-6.67-1.65-1.out            NaN  6.67      1.65              1
529  scf-6.67-1.65-5.out            NaN  6.67      1.65              5
539  scf-6.67-1.71-5.out            NaN  6.67      1.71              5
545  scf-6.67-1.78-1.out            NaN  6.67      1.78              1
546  scf-6.67-1.78-2.out            NaN  6.67      1.78              2
592  scf-6.80-1.71-3.out            NaN  6.80      1.71              3
599  scf-6.80-1.74-5.out            NaN  6.80      1.74              5
600  scf-6.80-1.78-1.out            NaN  6.80      1.78              1
602  scf-6.80-1.78-3.out            NaN  6.80      1.78              3

In [15]:
# Contas em que a energia n√£o convergiu no ibrav = 0.
df[
    df['Energia Total'].isna()
]

                      Arquivo  Energia Total     a  ratio_ca  num_estrutura
280  scf-6.18-1.49-0.25-1.out            NaN  6.18      1.49              1
388  scf-6.43-1.45-0.25-4.out            NaN  6.43      1.45              4
443  scf-6.55-1.45-0.25-4.out            NaN  6.55      1.45              4
519  scf-6.67-1.58-0.25-5.out            NaN  6.67      1.58              5
523  scf-6.67-1.61-0.25-4.out            NaN  6.67      1.61              4
554  scf-6.80-1.45-0.25-5.out            NaN  6.80      1.45              5
559  scf-6.80-1.49-0.25-5.out            NaN  6.80      1.49              5
568  scf-6.80-1.55-0.25-4.out            NaN  6.80      1.55              4
575  scf-6.80-1.61-0.25-1.out            NaN  6.80      1.61              1
602  scf-6.80-1.78-0.25-3.out            NaN  6.80      1.78              3

In [16]:
nao_convergiu_nosym: list[int] = df[df['Energia Total'].isna()].index.tolist()
nao_convergiu_sym = df_sym[df_sym['Energia Total'].isna()].index.tolist()

In [17]:
nao_convergiu_nosym, nao_convergiu_sym

([280, 388, 443, 519, 523, 554, 559, 568, 575, 602],
 [109,
  207,
  248,
  323,
  329,
  379,
  407,
  423,
  436,
  475,
  525,
  529,
  539,
  545,
  546,
  592,
  599,
  600,
  602])

In [18]:
df_sym.loc[nao_convergiu_sym]

                 Arquivo  Energia Total     a  ratio_ca  num_estrutura
109  scf-5.68-1.78-5.out            NaN  5.68      1.78              5
207  scf-5.93-1.71-3.out            NaN  5.93      1.71              3
248  scf-6.06-1.61-4.out            NaN  6.06      1.61              4
323  scf-6.18-1.74-4.out            NaN  6.18      1.74              4
329  scf-6.18-1.78-5.out            NaN  6.18      1.78              5
379  scf-6.30-1.74-5.out            NaN  6.30      1.74              5
407  scf-6.43-1.58-3.out            NaN  6.43      1.58              3
423  scf-6.43-1.68-4.out            NaN  6.43      1.68              4
436  scf-6.43-1.78-2.out            NaN  6.43      1.78              2
475  scf-6.55-1.68-1.out            NaN  6.55      1.68              1
525  scf-6.67-1.65-1.out            NaN  6.67      1.65              1
529  scf-6.67-1.65-5.out            NaN  6.67      1.65              5
539  scf-6.67-1.71-5.out            NaN  6.67      1.71              5
545  scf-6.67-1.78-1.out            NaN  6.67      1.78              1
546  scf-6.67-1.78-2.out            NaN  6.67      1.78              2
592  scf-6.80-1.71-3.out            NaN  6.80      1.71              3
599  scf-6.80-1.74-5.out            NaN  6.80      1.74              5
600  scf-6.80-1.78-1.out            NaN  6.80      1.78              1
602  scf-6.80-1.78-3.out            NaN  6.80      1.78              3

In [24]:
df.loc[nao_convergiu_nosym]

                      Arquivo  Energia Total     a  ratio_ca  num_estrutura
280  scf-6.18-1.49-0.25-1.out            NaN  6.18      1.49              1
388  scf-6.43-1.45-0.25-4.out            NaN  6.43      1.45              4
443  scf-6.55-1.45-0.25-4.out            NaN  6.55      1.45              4
519  scf-6.67-1.58-0.25-5.out            NaN  6.67      1.58              5
523  scf-6.67-1.61-0.25-4.out            NaN  6.67      1.61              4
554  scf-6.80-1.45-0.25-5.out            NaN  6.80      1.45              5
559  scf-6.80-1.49-0.25-5.out            NaN  6.80      1.49              5
568  scf-6.80-1.55-0.25-4.out            NaN  6.80      1.55              4
575  scf-6.80-1.61-0.25-1.out            NaN  6.80      1.61              1
602  scf-6.80-1.78-0.25-3.out            NaN  6.80      1.78              3

In [ ]:
df.loc[nao_convergiu_nosym].groupby(by=['a', 'ratio_ca']).count()

               Arquivo  Energia Total  num_estrutura
a    ratio_ca
6.18 1.49            1              0              1
6.43 1.45            1              0              1
6.55 1.45            1              0              1
6.67 1.58            1              0              1
     1.61            1              0              1
6.80 1.45            1              0              1
     1.49            1              0              1
     1.55            1              0              1
     1.61            1              0              1
     1.78            1              0              1

In [20]:
df_sym.loc[nao_convergiu_sym].groupby(by=['a', 'ratio_ca']).count()

               Arquivo  Energia Total  num_estrutura
a    ratio_ca
5.68 1.78            1              0              1
5.93 1.71            1              0              1
6.06 1.61            1              0              1
6.18 1.74            1              0              1
     1.78            1              0              1
6.30 1.74            1              0              1
6.43 1.58            1              0              1
     1.68            1              0              1
     1.78            1              0              1
6.55 1.68            1              0              1
6.67 1.65            2              0              2
     1.71            1              0              1
     1.78            2              0              2
6.80 1.71            1              0              1
     1.74            1              0              1
     1.78            2              0              2

In [21]:
df_sym.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Arquivo        605 non-null    object
 1   Energia Total  586 non-null    float64
 2   a              605 non-null    float64
 3   ratio_ca       605 non-null    float64
 4   num_estrutura  605 non-null    int64
dtypes: float64(3), int64(1), object(1)
memory usage: 23.8+ KB

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Arquivo        605 non-null    object
 1   Energia Total  595 non-null    float64
 2   a              605 non-null    float64
 3   ratio_ca       605 non-null    float64
 4   num_estrutura  605 non-null    int64
dtypes: float64(3), int64(1), object(1)
memory usage: 23.8+ KB

In [23]:
df_sym[ df_sym['Energia Total'].isna()].info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, 109 to 602
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Arquivo        19 non-null     object
 1   Energia Total  0 non-null      float64
 2   a              19 non-null     float64
 3   ratio_ca       19 non-null     float64
 4   num_estrutura  19 non-null     int64
dtypes: float64(3), int64(1), object(1)
memory usage: 912.0+ bytes